Migrate to Che Release 5.11.0 fixes #24
eclipsesource/emf4che pull request #25
Opened 2017-05-29 13:26 UTC by mathansen

Signed-off-by: Mat Hansen <mhansen@eclipsesource.com>

2017-05-29 14:19 UTC, sdirix commented
Thanks for including the new "start.sh". Good idea!

There are two issues:
- Please update the README.md (Run chapter) to reflect the version change
- When the built Che is run, it reports incompatible version for the scripts. It seems that the copied "dockerfiles" are from the 5.11.1 release instead of the 5.11.0. Please change the PR to include the 5.11.0 files. You can make sure by checking out the tag "5.11.0" of the Che repository.

2017-05-29 14:28 UTC, sdirix requested changes
See submitted comment

2017-05-31 15:25 UTC, mathansen commented
Should be good to go now. Thank you for your changes!

2017-05-31 15:43 UTC, sdirix approved these changes

2017-05-31 15:43 UTC, merged